### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by npresseault**
## Description
Bump:
- AtomicFu from 0.17.0 to 0.17.1
- Jetpack Compose from 1.2.0-alpha03 to 1.2.0-alpha07
- Kotlinx.Coroutines from 1.6.0 to 1.6.1
- Ktor from 2.0.0-beta-1 to 2.0.0
- Kotlin to 1.6.20

### CODE REVIEW

**Review by marcantoinefortier — APPROVED** [review]
🎉

**Comment by marcantoinefortier** [comment]
Hey you forgot to bump to kotlin 1.6.20! :trollface:

**Comment by npresseault** [comment]
It hasn't made it in compose alpha-07 :(
I think the support is available in some kind of dev build but hasn't been merged yet https://android-review.googlesource.com/c/platform/frameworks/support/+/2020776/

**Comment by npresseault** [comment]
Ok bad news: ktor 2.0.0 uses kotlin 1.6.20 which is not compatible with 1.6.10 for JS IR.
(See https://kotlinlang.slack.com/archives/C0A974TJ9/p1649433641847869)

This bump will be on hold until we have a jetpack compose release for 1.6.20)

**Pull request merged**
